namespace QAAutomation.API.DTOs;

/// <summary>Request to run an automated audit against a form using LLM analysis of a call transcript.</summary>
public class AutoAuditRequestDto
{
    /// <summary>The evaluation form to score against.</summary>
    public int FormId { get; set; }

    /// <summary>The call transcript text to analyze.</summary>
    public string Transcript { get; set; } = string.Empty;

    /// <summary>Name of the agent being evaluated (optional — LLM will attempt to extract if empty).</summary>
    public string? AgentName { get; set; }

    /// <summary>Call reference / interaction ID.</summary>
    public string? CallReference { get; set; }

    /// <summary>Date of the call.</summary>
    public DateTime? CallDate { get; set; }

    /// <summary>Name of the QA evaluator requesting the auto-audit.</summary>
    public string EvaluatedBy { get; set; } = string.Empty;
}

/// <summary>The LLM-generated score for a single form field.</summary>
public class AutoAuditFieldScoreDto
{
    public int FieldId { get; set; }
    public string FieldLabel { get; set; } = string.Empty;
    public string SectionTitle { get; set; } = string.Empty;
    public int MaxRating { get; set; }
    public double SuggestedScore { get; set; }
    /// <summary>Final score — starts equal to SuggestedScore and may be adjusted by reviewer.</summary>
    public double FinalScore { get; set; }
    public string Reasoning { get; set; } = string.Empty;
    public string Value => FinalScore.ToString(System.Globalization.CultureInfo.InvariantCulture);
}

/// <summary>Full auto-audit analysis result from the LLM.</summary>
public class AutoAuditResponseDto
{
    public int FormId { get; set; }
    public string FormName { get; set; } = string.Empty;
    public string Transcript { get; set; } = string.Empty;
    /// <summary>Agent name (extracted from transcript or provided by user).</summary>
    public string? AgentName { get; set; }
    public string? CallReference { get; set; }
    public string EvaluatedBy { get; set; } = string.Empty;
    public DateTime? CallDate { get; set; }
    /// <summary>Per-field scores — named "Fields" to match the web AutoAuditReviewViewModel.</summary>
    public List<AutoAuditFieldScoreDto> Fields { get; set; } = new();
    public string OverallReasoning { get; set; } = string.Empty;
    public double TotalScore => Fields.Sum(s => s.FinalScore);
    public double MaxPossibleScore => Fields.Sum(s => s.MaxRating);
    public double ScorePercent => MaxPossibleScore > 0
        ? Math.Round(TotalScore / MaxPossibleScore * 100, 1) : 0;

    /// <summary>Whether the result was generated by a real LLM (true) or a mock/fallback (false).</summary>
    public bool IsAiGenerated { get; set; }

    /// <summary>Error message if analysis failed partially.</summary>
    public string? AnalysisError { get; set; }
}
