namespace QAAutomation.API.DTOs;

/// <summary>Request to run sentiment and emotion analysis on a call transcript.</summary>
public class SentimentAnalysisRequestDto
{
    /// <summary>The call transcript text to analyze.</summary>
    public string Transcript { get; set; } = string.Empty;

    /// <summary>Agent name hint (optional).</summary>
    public string? AgentName { get; set; }

    /// <summary>Name of the QA evaluator requesting the analysis.</summary>
    public string EvaluatedBy { get; set; } = string.Empty;
}

/// <summary>A single detected emotion for a speaker.</summary>
public class DetectedEmotionDto
{
    /// <summary>Emotion label (e.g. Empathy, Frustration, Professionalism, Relief).</summary>
    public string Emotion { get; set; } = string.Empty;
    /// <summary>Confidence 0–100.</summary>
    public double Confidence { get; set; }
    /// <summary>"Agent" or "Customer".</summary>
    public string Speaker { get; set; } = string.Empty;
}

/// <summary>A key moment identified in the call.</summary>
public class KeyMomentDto
{
    /// <summary>Short title for the moment (e.g. "Customer Escalation", "Resolution Reached").</summary>
    public string Title { get; set; } = string.Empty;
    /// <summary>"Positive", "Neutral", or "Negative".</summary>
    public string Sentiment { get; set; } = string.Empty;
    /// <summary>Short excerpt or paraphrase from the transcript.</summary>
    public string Excerpt { get; set; } = string.Empty;
}

/// <summary>A coaching recommendation for the agent.</summary>
public class CoachingRecommendationDto
{
    /// <summary>Category (e.g. Empathy, Communication, Compliance, Product Knowledge).</summary>
    public string Category { get; set; } = string.Empty;
    /// <summary>"High", "Medium", or "Low".</summary>
    public string Priority { get; set; } = string.Empty;
    /// <summary>Concrete, actionable recommendation text.</summary>
    public string Text { get; set; } = string.Empty;
    /// <summary>Evidence from the transcript that supports this recommendation.</summary>
    public string Evidence { get; set; } = string.Empty;
}

/// <summary>Full sentiment and emotion analysis result.</summary>
public class SentimentAnalysisResponseDto
{
    /// <summary>"Positive", "Neutral", or "Negative".</summary>
    public string OverallSentiment { get; set; } = string.Empty;
    /// <summary>0–100 confidence score.</summary>
    public double OverallScore { get; set; }

    public string AgentSentiment { get; set; } = string.Empty;
    public double AgentScore { get; set; }

    public string CustomerSentiment { get; set; } = string.Empty;
    public double CustomerScore { get; set; }

    /// <summary>"Improving", "Stable", or "Declining".</summary>
    public string SentimentTrend { get; set; } = string.Empty;

    public List<DetectedEmotionDto> DominantEmotions { get; set; } = new();
    public List<KeyMomentDto> KeyMoments { get; set; } = new();
    public List<CoachingRecommendationDto> Recommendations { get; set; } = new();

    /// <summary>2–3 sentence overall insight.</summary>
    public string OverallInsight { get; set; } = string.Empty;

    /// <summary>Whether results were generated by a real LLM.</summary>
    public bool IsAiGenerated { get; set; }

    public string? AnalysisError { get; set; }
}
