using OpenAI;
using OpenAI.Chat;
using System.ClientModel;

namespace QAAutomation.API.Services;

/// <summary>
/// Shared helpers for Azure OpenAI / Azure AI Foundry client configuration.
/// </summary>
internal static class AzureOpenAIHelper
{
    private const string DeploymentsMarker = "/openai/deployments/";
    private const string FoundryV1Path = "/openai/v1/";

    /// <summary>
    /// Normalizes the stored <paramref name="endpoint"/> to the Azure AI Foundry
    /// <c>/openai/v1/</c> base URL and resolves the effective deployment / model name.
    ///
    /// Three input forms are accepted:
    /// <list type="bullet">
    ///   <item>Full deployment URL copied from Azure Portal or earlier config, e.g.<br/>
    ///     <c>https://resource.cognitiveservices.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=…</c><br/>
    ///     → base URL extracted, deployment name parsed from path, Foundry suffix appended.</item>
    ///   <item>Foundry v1 endpoint already in the correct form, e.g.<br/>
    ///     <c>https://resource.cognitiveservices.azure.com/openai/v1/</c><br/>
    ///     → used as-is.</item>
    ///   <item>Plain resource base URL, e.g.<br/>
    ///     <c>https://resource.cognitiveservices.azure.com/</c><br/>
    ///     → <c>/openai/v1/</c> suffix appended.</item>
    /// </list>
    /// </summary>
    /// <param name="endpoint">The raw <c>LlmEndpoint</c> value from configuration.</param>
    /// <param name="deployment">The configured <c>LlmDeployment</c> value; may be overridden by a deployment name embedded in the URL.</param>
    /// <returns>A tuple of (<c>foundryEndpoint</c>, <c>effectiveDeployment</c>).</returns>
    public static (string Endpoint, string Deployment) NormalizeEndpoint(string endpoint, string deployment)
    {
        if (string.IsNullOrEmpty(endpoint))
            return (endpoint, deployment);

        // ── Case 1: full deployment URL (traditional Azure OpenAI or portal copy-paste) ──
        // e.g. https://resource.cognitiveservices.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=…
        var markerIdx = endpoint.IndexOf(DeploymentsMarker, StringComparison.OrdinalIgnoreCase);
        if (markerIdx >= 0)
        {
            var baseUrl = endpoint[..markerIdx].TrimEnd('/');

            // Extract the deployment name from the path segment following the marker
            var afterMarker = endpoint[(markerIdx + DeploymentsMarker.Length)..];
            var slashIdx = afterMarker.IndexOf('/');
            var urlDeployment = slashIdx >= 0 ? afterMarker[..slashIdx] : afterMarker;
            var queryIdx = urlDeployment.IndexOf('?');
            if (queryIdx >= 0) urlDeployment = urlDeployment[..queryIdx];

            // Prefer URL-embedded deployment only when none is explicitly configured
            var effectiveDeployment = string.IsNullOrWhiteSpace(deployment) && !string.IsNullOrWhiteSpace(urlDeployment)
                ? urlDeployment
                : deployment;

            return (baseUrl + FoundryV1Path, effectiveDeployment);
        }

        // ── Case 2: already a Foundry /openai/v1/ endpoint — use as-is ──
        if (endpoint.Contains(FoundryV1Path, StringComparison.OrdinalIgnoreCase))
            return (endpoint.TrimEnd('/') + "/", deployment);

        // ── Case 3: plain base URL — append the Foundry path ──
        return (endpoint.TrimEnd('/') + FoundryV1Path, deployment);
    }

    /// <summary>
    /// Creates a <see cref="ChatClient"/> configured for the Azure AI Foundry
    /// OpenAI-compatible endpoint.
    ///
    /// <see cref="ApiKeyCredential"/> sends the key as <c>Authorization: Bearer &lt;key&gt;</c>,
    /// matching the authentication format required by Azure AI Foundry resources and the
    /// sample code generated by the Foundry portal.  Both plain Azure OpenAI API keys and
    /// Entra ID access tokens are accepted in this header by the service.
    /// </summary>
    /// <param name="endpoint">Normalised Foundry base URL (e.g. <c>https://resource.cognitiveservices.azure.com/openai/v1/</c>).</param>
    /// <param name="apiKey">API key or Entra ID bearer token stored in <c>LlmApiKey</c>.</param>
    /// <param name="deployment">Model / deployment name (e.g. <c>gpt-4o</c>).</param>
    public static ChatClient CreateClient(string endpoint, string apiKey, string deployment) =>
        new(model: deployment,
            credential: new ApiKeyCredential(apiKey),
            options: new OpenAIClientOptions
            {
                Endpoint = new Uri(endpoint),
                // LLM completions for long transcripts can take several minutes;
                // the default 100-second SDK network timeout is too short and causes
                // TaskCanceledException / SocketException (995) on slow responses.
                NetworkTimeout = TimeSpan.FromMinutes(10)
            });
}
