using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using Microsoft.Extensions.DependencyInjection;
using QAAutomation.API.Data;
using QAAutomation.API.DTOs;
using QAAutomation.API.Models;
using Xunit;

namespace QAAutomation.Tests;

/// <summary>
/// Integration tests for the LLM-powered TNI Assessment module:
///   • GET  /api/tni/{id}/assessment  — assessment retrieval
///   • POST /api/tni/{id}/attempt     — answer submission and scoring
///   • GET  /api/tni/{id}/attempts    — attempt history
///   • GET  /api/tni/dashboard        — summary dashboard
/// LLM generation is not tested here (requires a live LLM endpoint).
/// These tests exercise the assessment and dashboard logic directly by seeding
/// AssessmentJson on the plan using the DB context.
/// </summary>
public class TniAssessmentTests : IClassFixture<TestWebApplicationFactory>
{
    private readonly HttpClient _client;
    private readonly TestWebApplicationFactory _factory;

    public TniAssessmentTests(TestWebApplicationFactory factory)
    {
        _factory = factory;
        _client = factory.CreateClient();
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private static object DefaultPlanDto(string title = "TNI Assessment Test") => new
    {
        title,
        description = "Auto-generated",
        agentName = "Test Agent",
        agentUsername = "test.agent",
        trainerName = "Test Trainer",
        trainerUsername = "test.trainer",
        dueDate = (DateTime?)null,
        projectId = (int?)null,
        evaluationResultId = (int?)null,
        humanReviewItemId = (int?)null,
        createdBy = "qm_user",
        isAutoGenerated = true,
        items = new[]
        {
            new { targetArea = "Compliance", itemType = "Observation", content = "Failed on compliance", order = 0 }
        }
    };

    private static readonly string SampleAssessmentJson = JsonSerializer.Serialize(new[]
    {
        new
        {
            question = "What is the correct way to verify customer identity?",
            options = new[] { "Ask for DOB", "Ask for account number only", "Use two-factor verification", "Skip verification" },
            correctIndex = 2,
            explanation = "Two-factor verification is the required process."
        },
        new
        {
            question = "When should you escalate a call?",
            options = new[] { "Never", "When you cannot resolve it", "Always", "After 5 minutes" },
            correctIndex = 1,
            explanation = "Escalate when the issue cannot be resolved at the current level."
        }
    });

    /// <summary>Creates a plan and seeds AssessmentJson + training content directly via DB context.</summary>
    private async Task<TrainingPlanDto> CreatePlanWithAssessmentAsync()
    {
        var r = await _client.PostAsJsonAsync("/api/trainingplans", DefaultPlanDto());
        r.EnsureSuccessStatusCode();
        var plan = (await r.Content.ReadFromJsonAsync<TrainingPlanDto>())!;

        // Seed assessment data directly via the DB context (bypasses LLM)
        using var scope = _factory.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        var entity = await db.TrainingPlans.FindAsync(plan.Id);
        entity!.LlmTrainingContent = "This is the LLM-generated training content covering compliance best practices.";
        entity.AssessmentJson = SampleAssessmentJson;
        entity.ContentGeneratedAt = DateTime.UtcNow;
        entity.AssessmentPassMark = 50; // 1 out of 2 correct = pass
        await db.SaveChangesAsync();

        return plan;
    }

    // ── GET /api/tni/{id}/assessment ─────────────────────────────────────────

    [Fact]
    public async Task GetAssessment_WhenAssessmentExists_ReturnsQuestionsWithoutAnswers()
    {
        var plan = await CreatePlanWithAssessmentAsync();

        var r = await _client.GetAsync($"/api/tni/{plan.Id}/assessment");
        Assert.Equal(HttpStatusCode.OK, r.StatusCode);

        var dto = await r.Content.ReadFromJsonAsync<TniAssessmentDto>();
        Assert.NotNull(dto);
        Assert.Equal(plan.Id, dto!.TrainingPlanId);
        Assert.Equal(2, dto.Questions.Count);
        Assert.NotEmpty(dto.TrainingContent);

        // Correct answers must NOT be exposed to agents
        Assert.All(dto.Questions, q => Assert.Null(q.CorrectIndex));
        Assert.All(dto.Questions, q => Assert.Null(q.Explanation));
    }

    [Fact]
    public async Task GetAssessment_WhenNoAssessmentGenerated_Returns400()
    {
        var r = await _client.PostAsJsonAsync("/api/trainingplans", DefaultPlanDto("No Assessment Plan"));
        r.EnsureSuccessStatusCode();
        var plan = (await r.Content.ReadFromJsonAsync<TrainingPlanDto>())!;

        var r2 = await _client.GetAsync($"/api/tni/{plan.Id}/assessment");
        Assert.Equal(HttpStatusCode.BadRequest, r2.StatusCode);
    }

    [Fact]
    public async Task GetAssessment_NonExistentPlan_Returns404()
    {
        var r = await _client.GetAsync("/api/tni/99999/assessment");
        Assert.Equal(HttpStatusCode.NotFound, r.StatusCode);
    }

    // ── POST /api/tni/{id}/attempt ────────────────────────────────────────────

    [Fact]
    public async Task SubmitAttempt_AllCorrect_ReturnsPassWithFeedback()
    {
        var plan = await CreatePlanWithAssessmentAsync();

        var submitDto = new { agentUsername = "test.agent", answers = new[] { 2, 1 } }; // both correct
        var r = await _client.PostAsJsonAsync($"/api/tni/{plan.Id}/attempt", submitDto);
        Assert.Equal(HttpStatusCode.OK, r.StatusCode);

        var result = await r.Content.ReadFromJsonAsync<TniAttemptResultDto>();
        Assert.NotNull(result);
        Assert.Equal("Pass", result!.Result);
        Assert.Equal(2, result.CorrectAnswers);
        Assert.Equal(2, result.TotalQuestions);
        Assert.Equal(100.0, result.ScorePercent);
        Assert.Equal(2, result.Feedback.Count);
        Assert.All(result.Feedback, f => Assert.True(f.IsCorrect));
        // Explanations should be returned after submission
        Assert.All(result.Feedback, f => Assert.NotNull(f.Explanation));
    }

    [Fact]
    public async Task SubmitAttempt_AllWrong_ReturnsFail()
    {
        var plan = await CreatePlanWithAssessmentAsync();

        var submitDto = new { agentUsername = "test.agent", answers = new[] { 0, 0 } }; // both wrong
        var r = await _client.PostAsJsonAsync($"/api/tni/{plan.Id}/attempt", submitDto);
        Assert.Equal(HttpStatusCode.OK, r.StatusCode);

        var result = await r.Content.ReadFromJsonAsync<TniAttemptResultDto>();
        Assert.NotNull(result);
        Assert.Equal("Fail", result!.Result);
        Assert.Equal(0, result.CorrectAnswers);
        Assert.Equal(0.0, result.ScorePercent);
    }

    [Fact]
    public async Task SubmitAttempt_WrongAnswerCount_Returns400()
    {
        var plan = await CreatePlanWithAssessmentAsync();

        // Only 1 answer for 2 questions
        var submitDto = new { agentUsername = "test.agent", answers = new[] { 2 } };
        var r = await _client.PostAsJsonAsync($"/api/tni/{plan.Id}/attempt", submitDto);
        Assert.Equal(HttpStatusCode.BadRequest, r.StatusCode);
    }

    [Fact]
    public async Task SubmitAttempt_PersistsAndReturnsAttemptId()
    {
        var plan = await CreatePlanWithAssessmentAsync();

        var submitDto = new { agentUsername = "alice", answers = new[] { 2, 1 } };
        var r = await _client.PostAsJsonAsync($"/api/tni/{plan.Id}/attempt", submitDto);
        r.EnsureSuccessStatusCode();

        var result = await r.Content.ReadFromJsonAsync<TniAttemptResultDto>();
        Assert.True(result!.AttemptId > 0);
        Assert.Equal("alice", result.AgentUsername);
    }

    // ── GET /api/tni/{id}/attempts ────────────────────────────────────────────

    [Fact]
    public async Task GetAttempts_ReturnsHistoryForPlan()
    {
        var plan = await CreatePlanWithAssessmentAsync();

        // Submit two attempts
        await _client.PostAsJsonAsync($"/api/tni/{plan.Id}/attempt",
            new { agentUsername = "bob", answers = new[] { 2, 1 } });
        await _client.PostAsJsonAsync($"/api/tni/{plan.Id}/attempt",
            new { agentUsername = "bob", answers = new[] { 0, 0 } });

        var r = await _client.GetAsync($"/api/tni/{plan.Id}/attempts");
        Assert.Equal(HttpStatusCode.OK, r.StatusCode);

        var attempts = await r.Content.ReadFromJsonAsync<List<TniAttemptResultDto>>();
        Assert.NotNull(attempts);
        Assert.True(attempts!.Count >= 2);
    }

    [Fact]
    public async Task GetAttempts_FilterByAgent_ReturnsOnlyThatAgent()
    {
        var plan = await CreatePlanWithAssessmentAsync();

        await _client.PostAsJsonAsync($"/api/tni/{plan.Id}/attempt",
            new { agentUsername = "agent_x", answers = new[] { 2, 1 } });
        await _client.PostAsJsonAsync($"/api/tni/{plan.Id}/attempt",
            new { agentUsername = "agent_y", answers = new[] { 0, 0 } });

        var r = await _client.GetAsync($"/api/tni/{plan.Id}/attempts?agentUsername=agent_x");
        r.EnsureSuccessStatusCode();

        var attempts = await r.Content.ReadFromJsonAsync<List<TniAttemptResultDto>>();
        Assert.All(attempts!, a => Assert.Equal("agent_x", a.AgentUsername));
    }

    // ── GET /api/tni/dashboard ────────────────────────────────────────────────

    [Fact]
    public async Task Dashboard_ReturnsAggregatedStats()
    {
        var plan = await CreatePlanWithAssessmentAsync();

        var r = await _client.GetAsync("/api/tni/dashboard");
        Assert.Equal(HttpStatusCode.OK, r.StatusCode);

        var dash = await r.Content.ReadFromJsonAsync<TniDashboardDto>();
        Assert.NotNull(dash);
        Assert.True(dash!.TotalPlans >= 1);
        Assert.True(dash.PlansWithAssessment >= 1);
        // Our plan has no attempt yet so it should be Pending
        var item = dash.Items.FirstOrDefault(i => i.PlanId == plan.Id);
        Assert.NotNull(item);
        Assert.Equal("Pending", item!.AssessmentStatus);
        Assert.True(item.HasAssessment);
    }

    [Fact]
    public async Task Dashboard_AfterPassAttempt_ShowsPassStatus()
    {
        var plan = await CreatePlanWithAssessmentAsync();

        await _client.PostAsJsonAsync($"/api/tni/{plan.Id}/attempt",
            new { agentUsername = "test.agent", answers = new[] { 2, 1 } }); // Pass

        var r = await _client.GetAsync("/api/tni/dashboard");
        r.EnsureSuccessStatusCode();
        var dash = await r.Content.ReadFromJsonAsync<TniDashboardDto>();

        var item = dash!.Items.FirstOrDefault(i => i.PlanId == plan.Id);
        Assert.Equal("Pass", item!.AssessmentStatus);
        Assert.Equal(100.0, item.LatestScore);
        Assert.Equal(1, item.AttemptCount);
    }

    [Fact]
    public async Task Dashboard_AfterFailAttempt_ShowsFailStatus()
    {
        var plan = await CreatePlanWithAssessmentAsync();

        await _client.PostAsJsonAsync($"/api/tni/{plan.Id}/attempt",
            new { agentUsername = "test.agent", answers = new[] { 0, 0 } }); // Fail

        var r = await _client.GetAsync("/api/tni/dashboard");
        r.EnsureSuccessStatusCode();
        var dash = await r.Content.ReadFromJsonAsync<TniDashboardDto>();

        var item = dash!.Items.FirstOrDefault(i => i.PlanId == plan.Id);
        Assert.Equal("Fail", item!.AssessmentStatus);
    }

    // ── GetAssessment with agentUsername — shows latest attempt ──────────────

    [Fact]
    public async Task GetAssessment_WithAgentUsername_IncludesLatestAttempt()
    {
        var plan = await CreatePlanWithAssessmentAsync();

        await _client.PostAsJsonAsync($"/api/tni/{plan.Id}/attempt",
            new { agentUsername = "carol", answers = new[] { 2, 1 } });

        var r = await _client.GetAsync($"/api/tni/{plan.Id}/assessment?agentUsername=carol");
        r.EnsureSuccessStatusCode();

        var dto = await r.Content.ReadFromJsonAsync<TniAssessmentDto>();
        Assert.NotNull(dto!.LatestAttempt);
        Assert.Equal("carol", dto.LatestAttempt!.AgentUsername);
        Assert.Equal("Pass", dto.LatestAttempt.Result);
    }

    // ── POST /api/tni/{id}/generate without LLM — returns 400 ────────────────

    [Fact]
    public async Task Generate_WhenLlmNotConfigured_Returns400()
    {
        var plan = await CreatePlanWithAssessmentAsync();

        // LLM is not configured in test environment
        var r = await _client.PostAsJsonAsync($"/api/tni/{plan.Id}/generate",
            new { questionCount = 3 });
        // Should fail gracefully with 400 (LLM not configured)
        Assert.Equal(HttpStatusCode.BadRequest, r.StatusCode);
    }
}
